controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

kernel:
    resource: App\Kernel
    type: attribute


verify.email:
    path: /verify/email
    controller: App\Controller\RegistrationController::verifyUserEmail